package Informacion;
// Generated May 7, 2018 7:07:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bodega generated by hbm2java
 */
public class Bodega  implements java.io.Serializable {


     private Integer idbodega;
     private String nombre;
     private String direccion;
     private String telefono;
     private Set<Inventario> inventarios = new HashSet<Inventario>(0);

    public Bodega() {
    }

    public Bodega(String nombre, String direccion, String telefono, Set<Inventario> inventarios) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.inventarios = inventarios;
    }
   
    public Integer getIdbodega() {
        return this.idbodega;
    }
    
    public void setIdbodega(Integer idbodega) {
        this.idbodega = idbodega;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Inventario> getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set<Inventario> inventarios) {
        this.inventarios = inventarios;
    }




}


