package Informacion;
// Generated May 7, 2018 7:07:22 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private ClientesId id;
     private String direccion;
     private String ciudad;
     private String telefono;
     private String contacto;
     private String email;
     private String obs;
     private Integer terminos;
     private BigDecimal limite;

    public Clientes() {
    }

	
    public Clientes(ClientesId id) {
        this.id = id;
    }
    public Clientes(ClientesId id, String direccion, String ciudad, String telefono, String contacto, String email, String obs, Integer terminos, BigDecimal limite) {
       this.id = id;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.telefono = telefono;
       this.contacto = contacto;
       this.email = email;
       this.obs = obs;
       this.terminos = terminos;
       this.limite = limite;
    }
   
    public ClientesId getId() {
        return this.id;
    }
    
    public void setId(ClientesId id) {
        this.id = id;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getObs() {
        return this.obs;
    }
    
    public void setObs(String obs) {
        this.obs = obs;
    }
    public Integer getTerminos() {
        return this.terminos;
    }
    
    public void setTerminos(Integer terminos) {
        this.terminos = terminos;
    }
    public BigDecimal getLimite() {
        return this.limite;
    }
    
    public void setLimite(BigDecimal limite) {
        this.limite = limite;
    }




}


