package Informacion;
// Generated May 7, 2018 7:07:22 PM by Hibernate Tools 4.3.1



/**
 * ClientesId generated by hbm2java
 */
public class ClientesId  implements java.io.Serializable {


     private String nombre;
     private String nit;

    public ClientesId() {
    }

    public ClientesId(String nombre, String nit) {
       this.nombre = nombre;
       this.nit = nit;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClientesId) ) return false;
		 ClientesId castOther = ( ClientesId ) other; 
         
		 return ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) )
 && ( (this.getNit()==castOther.getNit()) || ( this.getNit()!=null && castOther.getNit()!=null && this.getNit().equals(castOther.getNit()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         result = 37 * result + ( getNit() == null ? 0 : this.getNit().hashCode() );
         return result;
   }   


}


