package Informacion;
// Generated May 7, 2018 7:07:22 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detallefactura generated by hbm2java
 */
public class Detallefactura  implements java.io.Serializable {


     private int idfactura;
     private Articulo articulo;
     private Factura factura;
     private BigDecimal cantidad;

    public Detallefactura() {
    }

	
    public Detallefactura(Factura factura) {
        this.factura = factura;
    }
    public Detallefactura(Articulo articulo, Factura factura, BigDecimal cantidad) {
       this.articulo = articulo;
       this.factura = factura;
       this.cantidad = cantidad;
    }
   
    public int getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(int idfactura) {
        this.idfactura = idfactura;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


