package Informacion;
// Generated May 7, 2018 7:07:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int idfactura;
     private Empleado empleado;
     private String nit;
     private String nombre;
     private Date fecha;
     private Detallefactura detallefactura;

    public Factura() {
    }

	
    public Factura(int idfactura) {
        this.idfactura = idfactura;
    }
    public Factura(int idfactura, Empleado empleado, String nit, String nombre, Date fecha, Detallefactura detallefactura) {
       this.idfactura = idfactura;
       this.empleado = empleado;
       this.nit = nit;
       this.nombre = nombre;
       this.fecha = fecha;
       this.detallefactura = detallefactura;
    }
   
    public int getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(int idfactura) {
        this.idfactura = idfactura;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Detallefactura getDetallefactura() {
        return this.detallefactura;
    }
    
    public void setDetallefactura(Detallefactura detallefactura) {
        this.detallefactura = detallefactura;
    }




}


