package Informacion;
// Generated May 7, 2018 7:07:22 PM by Hibernate Tools 4.3.1



/**
 * InventarioId generated by hbm2java
 */
public class InventarioId  implements java.io.Serializable {


     private String idarticulo;
     private int idbodega;

    public InventarioId() {
    }

    public InventarioId(String idarticulo, int idbodega) {
       this.idarticulo = idarticulo;
       this.idbodega = idbodega;
    }
   
    public String getIdarticulo() {
        return this.idarticulo;
    }
    
    public void setIdarticulo(String idarticulo) {
        this.idarticulo = idarticulo;
    }
    public int getIdbodega() {
        return this.idbodega;
    }
    
    public void setIdbodega(int idbodega) {
        this.idbodega = idbodega;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InventarioId) ) return false;
		 InventarioId castOther = ( InventarioId ) other; 
         
		 return ( (this.getIdarticulo()==castOther.getIdarticulo()) || ( this.getIdarticulo()!=null && castOther.getIdarticulo()!=null && this.getIdarticulo().equals(castOther.getIdarticulo()) ) )
 && (this.getIdbodega()==castOther.getIdbodega());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdarticulo() == null ? 0 : this.getIdarticulo().hashCode() );
         result = 37 * result + this.getIdbodega();
         return result;
   }   


}


