package Informacion;
// Generated May 7, 2018 7:07:22 PM by Hibernate Tools 4.3.1



/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private InventarioId id;
     private Articulo articulo;
     private Bodega bodega;
     private int cantidad;

    public Inventario() {
    }

    public Inventario(InventarioId id, Articulo articulo, Bodega bodega, int cantidad) {
       this.id = id;
       this.articulo = articulo;
       this.bodega = bodega;
       this.cantidad = cantidad;
    }
   
    public InventarioId getId() {
        return this.id;
    }
    
    public void setId(InventarioId id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Bodega getBodega() {
        return this.bodega;
    }
    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


