package Informacion;
// Generated May 7, 2018 7:07:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idproveedor;
     private String nombre;
     private String telefono;
     private String contacto;
     private String direccion;
     private Set<Articulo> articulos = new HashSet<Articulo>(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombre) {
        this.nombre = nombre;
    }
    public Proveedor(String nombre, String telefono, String contacto, String direccion, Set<Articulo> articulos) {
       this.nombre = nombre;
       this.telefono = telefono;
       this.contacto = contacto;
       this.direccion = direccion;
       this.articulos = articulos;
    }
   
    public Integer getIdproveedor() {
        return this.idproveedor;
    }
    
    public void setIdproveedor(Integer idproveedor) {
        this.idproveedor = idproveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set<Articulo> getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set<Articulo> articulos) {
        this.articulos = articulos;
    }




}


