package Informacion;
// Generated May 7, 2018 7:07:22 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idusuario;
     private Empleado empleado;
     private Rol rol;
     private String password;
     private Boolean estado;

    public Usuario() {
    }

	
    public Usuario(String idusuario, Empleado empleado, Rol rol, String password) {
        this.idusuario = idusuario;
        this.empleado = empleado;
        this.rol = rol;
        this.password = password;
    }
    public Usuario(String idusuario, Empleado empleado, Rol rol, String password, Boolean estado) {
       this.idusuario = idusuario;
       this.empleado = empleado;
       this.rol = rol;
       this.password = password;
       this.estado = estado;
    }
   
    public String getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


