//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public string serie { get; set; }
        public string numero { get; set; }
        public string idProducto { get; set; }
        public decimal cantidad { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
