//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int idDocumento { get; set; }
        public string idTipoDocumento { get; set; }
        public string nit { get; set; }
        public string contactoReceptor { get; set; }
        public string username { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
